### ISSUE TITLE
`default_packages` default value of `false` appears to be ignored

### ISSUE THREAD

**Issue by p4t5h3** [SublimeText/syntax-test-action#11]
I have copied [the usage snippet](https://github.com/SublimeText/syntax-test-action#usage) into [my package project](https://github.com/peterthomashorn/purebasic-language-for-sublime-text/blob/main/.github/workflows/main.yml). When the action is run, then [the SublimeText/syntax-test-action@v2 fails](https://github.com/peterthomashorn/purebasic-language-for-sublime-text/runs/4092063197?check_suite_focus=true).

To me it looks like the default value for the input is not used:

> Fetching default packages (ref: , tests: false)
>  /tmp/tmp.3jzkggdKKn ~/work/purebasic-language-for-sublime-text/purebasic-language-for-sublime-text
>  --2021-11-03 11:58:13--  https://github.com/sublimehq/Packages/archive/.tar.gz

At a quick glance I see no error in the action.yml or the shell script. Or am I or is the snippet missing some additional information on how to get started?

**Comment by FichteFoll** [comment]
I checked a few other repositories that I found via github search and they don't seem to specify a ref for the default packages either ([1], [2]). 

Later I realized that in your snippet, it rather seems as if an empty string was used as the ref instead of `false` as a boolean, so I fixed the template to not include that by default. Thanks for reporting and sorry for not replying earlier.

[1]: https://github.com/eirik-kjonstad/modern-fortran-syntax/runs/4908456845?check_suite_focus=true
[2]: https://github.com/jwortmann/ini-syntax/runs/4997374971?check_suite_focus=true
