### ISSUE TITLE
Any file that begins with `syntax_test` will be tested

### ISSUE THREAD

**Issue by nk9** [SublimeText/syntax-test-action#14]
I have a file in my package called `assets/syntax_test_results.png`. This is used in my README. The action finds this file and attempts to run it:

```
/home/runner/work/just_sublime/syntax_tests/Data/Packages/Just/assets/syntax_test_results.png:1: unable to find SYNTAX TEST marker
[...]
Error: Process completed with exit code 1.
```

There are several solutions to this. As a workaround, I'm going to change the name of the file. But it should be possible to either provide some sort of include pattern for files/paths/types to test, or else allow exclusion files/paths.

**Comment by FichteFoll** [comment]
Testing all files that start with `syntax_test` is Sublime Text behavior that is should be consistent with the tests you can run from within the editor itself. To reproduce the error locally, just run `Build With: Syntax Tests - All Syntaxes` from the Command palette with a syntax test file active and it should show up in the log.

As such, the only way to get rid of such an error message would be to delete the file from the file system or rename it before invoking the syntax test binary.

However, considering how this behavior is consistent with the actual ST behavior and should reproduce locally (which I didn't verify), I'd rather suggest you to rename your file in-repo instead of having this as a configuration in the github action.

**Comment by nk9** [comment]
I didn't know about the `All Syntaxes` test, thanks for pointing that out. I've verified that the failure occurs when I use that Build System as well, so I'll close this.
