### ISSUE TITLE
Map failures back to lines/columns

### ISSUE THREAD

**Issue by michaelblyons** [SublimeText/syntax-test-action#7]
Some GitHub actions appear to be able to annotate the file in a PR or a commit. If there's a way to group consecutive failures<sup>1</sup> and do this annotation, I think that'd be a good enhancement.

I'm having trouble finding an example of the annotations, but I _know_ I've seen them before.

<sup>1</sup> syntax_test_foo:3:7 did not match `support`, syntax_test_foo:3:8 did not match `support`, syntax_test_foo:3:9 ...

**Comment by FichteFoll** [comment]
We should already be doing that, although I don't currently have a sample log to show.

https://github.com/SublimeText/syntax-test-action/blob/cd9fa51ddd87ad43b77c8f918bb7788b3f6adc52/syntax-tests.sh#L88-L94

The showing annotations in the failing runs (and pull requests), I mean. Not the grouping.

**Comment by michaelblyons** [comment]
Ah, okay. Do those show up on lines that didn't change within the commit? (Or maybe GitHub is just some issues right now?)

**Comment by FichteFoll** [comment]
They should but only when viewing the action itself iirc and not the PR's changes, or something similar. I wanted to provide some examples from the PackageDev repo where I know we had some failures before in PRs (because things changed upstream), but all the logs have since been deleted. Maybe you could set up a test situation/repo/PR to confirm your assumptions?

**Comment by michaelblyons** [comment]
If there's a way to get to the annotations from [this failure](https://github.com/michaelblyons/PowerShell/runs/2366910813), I'd be happy to learn it.

Obviously in _this_ instance I know where the failures are, and I can test the thing myself, but it'd be helpful for other people's PRs (if they have failures) to point to a URL showing what went wrong.

**Comment by FichteFoll** [comment]
Hm, I think there might be a bug in how the file path is "fixed", looking at it again. Unfortunately, the "raw log" isn't really raw, so I can't use past runs for debugging.

**Comment by FichteFoll** [comment]
Looks correct to me.
https://github.com/SublimeText/syntax-test-action/runs/2380510723?check_suite_focus=true#step:3:242

I made a test PR that also shows the annotations: https://github.com/SublimeText/syntax-test-action/pull/8/files

I would have expected the affected files and their line numbers to also show on https://github.com/SublimeText/syntax-test-action/actions/runs/763518336 (like the do [in the docs for Checks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks#checks)), but it seems I misremembered and they really only show on the PR itself. They don't show on the commit either (https://github.com/SublimeText/syntax-test-action/commit/6edbb596e22c617b7eb6ac42c4c8184187450386).

**Comment by FichteFoll** [comment]
I did a little more investigation and it seems that annotations with more surface are available to the Checks API only, which can be interfaced with through https://github.com/marketplace/actions/github-checks but is not something that I'd be particularly interested in integrating here. Seems way more complex that it needs to be.

According to [a forum post](https://github.community/t/what-are-annotations/16173/2), checks are coming to actions, but I didn't find anything specifically in the documentation or otherwise. I also didn't spend that much time looking, so that may also be wrong or outdated.

Closing since I don't see something actionable or worth spending time on other than what we already have.
